name: Docker

on:
  push:
    branches: [ master ]
    paths: 
      - '.docker/**'
      - '.github/**'
  pull_request:
    branches: [ master ]
    paths: 
      - '.docker/**'
      - '.github/**'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Publish Image
      uses: matootie/github-docker@v2.2.2
      with:
        accessToken: ${{ secrets.GITHUB_TOKEN }}
        context: .docker 
    
